version: "3.3"
services:
  mongodb:
    image : mongo
    container_name: mongod
    volumes:
      - /home/vagrant/ms_shippingchallenge/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  web:
    image: nginx
    container_name: nginx
    volumes:
      - /home/vagrant/ms_shippingchallenge/html:/usr/share/nginx/html
    ports:
      - "8000:80"
  perl:
    image: perl
    container_name: perl
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/vagrant/ms_shippingchallenge/html:/usr/src/myapp
    restart: always
    links:
      - mongodb
